package selenium;
 // Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
public class PruebaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void PruebaTest() {
    String email = "test010101010101221@test.cl";
    driver.get("http://automationpractice.com/index.php");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.cssSelector(".replace-2x")).click();
    driver.findElement(By.cssSelector(".exclusive > span")).click();
    driver.findElement(By.id("add_to_cart")).click();
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    driver.findElement(By.linkText("Proceed to checkout")).click();
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    driver.findElement(By.linkText("Proceed to checkout")).click();
    driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
    //driver.findElement(By.id("email_create")).sendKeys("test100000002@test.cl");


    driver.findElement(By.id("email_create")).click();
    {
      WebElement element = driver.findElement(By.id("email_create"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email_create")).click();
    {
      WebElement element = driver.findElement(By.id("email_create"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email_create")).click();
    driver.findElement(By.id("email_create")).sendKeys(email);
    driver.findElement(By.cssSelector("#SubmitCreate > span")).click();
    driver.findElement(By.id("customer_firstname")).click();
    driver.findElement(By.id("customer_firstname")).sendKeys("Claudio");
    driver.findElement(By.id("customer_lastname")).sendKeys("Suau");
    driver.findElement(By.id("email")).click();
    {
      WebElement element = driver.findElement(By.id("email"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("email")).click();
    
    //String emailValidar = driver.findElement(By.id("email")).value;
    //System.out.println("emailValidar");
    //System.out.println(emailValidar);
    //assertEquals(email,emailValidar);
    
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.cssSelector(".password")).click();
    driver.findElement(By.id("passwd")).click();
    driver.findElement(By.id("passwd")).sendKeys("gSB@5dv@gM@twKk");

    driver.findElement(By.id("address1")).click();
    driver.findElement(By.id("address1")).sendKeys("Barrio Alto 1");
    driver.findElement(By.id("address2")).click();
    driver.findElement(By.id("city")).click();
    driver.findElement(By.id("city")).sendKeys("Santiago");
    driver.findElement(By.id("postcode")).click();
    driver.findElement(By.id("postcode")).sendKeys("12345");
    driver.findElement(By.id("id_state")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Georgia']")).click();
    }
    driver.findElement(By.id("id_country")).click();
    driver.findElement(By.id("phone_mobile")).click();
    driver.findElement(By.id("phone_mobile")).sendKeys("9123456789");
    driver.findElement(By.id("alias")).click();
    driver.findElement(By.cssSelector("#submitAccount > span")).click();
    driver.findElement(By.cssSelector(".button:nth-child(4) > span")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".fancybox-item")).click();
    driver.findElement(By.id("cgv")).click();
    driver.findElement(By.cssSelector(".standard-checkout > span")).click();
    driver.findElement(By.cssSelector(".bankwire > span")).click();
    driver.findElement(By.cssSelector("#cart_navigation span")).click();
  }
}
